env:
  es6: true
  mocha: true
  node: true

extends:
  - eslint:recommended
  - plugin:node/recommended

plugins:
  - node
  - promise

rules:
  node/no-unpublished-require: off
  node/no-unsupported-features: [error, 6]

  promise/always-return: 2
  promise/catch-or-return: 2
  promise/no-native: 0
  promise/param-names: 2

  indent: [error, 2]
  linebreak-style: [error, unix]
  no-console: warn
  no-var: error
  prefer-const: error
  quotes: [error, single]
  semi: [error, always]
